# Numpy

In [1]:
import numpy as np

Arreglos unidimensionales

In [2]:
a = np.array([1,2,3,4,5,6,7,8])

In [3]:
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [4]:
a = np.array(range(10))

In [5]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
b = np.array([range(3), range(3), range(3)])

In [7]:
b

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

Utilidades para crear arreglos

In [9]:
# Arreglos de ceros
c = np.zeros(10)

In [10]:
c

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
# Usando shapes
d = np.zeros((3,3))
d

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [12]:
# También con ones
e = np.ones((4,4))
e

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
# O en genera con cualquier valor arbitrario
f = np.full((2,2), 3)
f

array([[3, 3],
       [3, 3]])

In [14]:
# Matrices de identidad
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [16]:
# Matrices con números aleatorios [0,1]
np.random.random((3,3))

array([[0.45209037, 0.03627838, 0.51350562],
       [0.88525188, 0.78281209, 0.65985674],
       [0.14620248, 0.71156407, 0.31838705]])

In [17]:
# Trabajando con aleatorios
np.random.sample()

0.8078358389305412

In [18]:
# Ahora cada arreglo de numpy tiene un shape, un size, un ndim y un type
a.shape

(10,)

In [19]:
a.ndim

1

In [20]:
a.size

10

In [21]:
a.dtype

dtype('int64')

In [22]:
# Numpy define sus propios tipos
type(a)

numpy.ndarray

In [26]:
# Reshaping
# Si el tamaño lo permite, se puede cambiar la forma del ndarray
a = np.array([1,2,3,4,5,6,7,8,9])
a_reshape = a.reshape((3,3))
a_reshape

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
# También funcionan los slices
a_reshape[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [41]:
a_reshape[:,1:3]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [43]:
# Y de alto nivel
a = np.array(range(16)).reshape((4,4))
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [47]:
a[2:4,1:3]

array([[ 9, 10],
       [13, 14]])

In [48]:
# Ahora también se puede asignar a un solo valor todo un subconjunto
a[2:4,1:3] = 0
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  0,  0, 11],
       [12,  0,  0, 15]])

In [51]:
# o a un arreglo
a[2:4,1:3] = np.array(range(4)).reshape((2,2))
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  0,  1, 11],
       [12,  2,  3, 15]])

In [52]:
# Condicionales
a = np.array(range(9))
a > 5

array([False, False, False, False, False, False,  True,  True,  True])

In [54]:
# Funciona con ndimenssionales tambien
a.reshape((3,3)) > 5

array([[False, False, False],
       [False, False, False],
       [ True,  True,  True]])

In [55]:
# Y los filtros
a[a>5]

array([6, 7, 8])

In [56]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [59]:
# Ahora los reshapes repitiendo valores
b = np.resize(a,(4,4))
b

array([[0, 1, 2, 3],
       [4, 5, 6, 7],
       [8, 0, 1, 2],
       [3, 4, 5, 6]])

In [60]:
# Y sacar la matriz inversa
b.T

array([[0, 4, 8, 3],
       [1, 5, 0, 4],
       [2, 6, 1, 5],
       [3, 7, 2, 6]])

In [66]:
# O multiplicar arreglso
np.broadcast_to(a, (3,9))

array([[0, 1, 2, 3, 4, 5, 6, 7, 8],
       [0, 1, 2, 3, 4, 5, 6, 7, 8],
       [0, 1, 2, 3, 4, 5, 6, 7, 8]])

In [68]:
b = np.array(range(16)).reshape((4,4))
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [71]:
c = np.copy(b) - 16
c

array([[-16, -15, -14, -13],
       [-12, -11, -10,  -9],
       [ -8,  -7,  -6,  -5],
       [ -4,  -3,  -2,  -1]])

In [74]:
# Concatenar arreglos
np.concatenate((b,c), axis=0)

array([[  0,   1,   2,   3],
       [  4,   5,   6,   7],
       [  8,   9,  10,  11],
       [ 12,  13,  14,  15],
       [-16, -15, -14, -13],
       [-12, -11, -10,  -9],
       [ -8,  -7,  -6,  -5],
       [ -4,  -3,  -2,  -1]])

In [75]:
np.concatenate((b,c), axis=1)

array([[  0,   1,   2,   3, -16, -15, -14, -13],
       [  4,   5,   6,   7, -12, -11, -10,  -9],
       [  8,   9,  10,  11,  -8,  -7,  -6,  -5],
       [ 12,  13,  14,  15,  -4,  -3,  -2,  -1]])

In [76]:
# Apilar arreglos
np.stack((b,c),0)

array([[[  0,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11],
        [ 12,  13,  14,  15]],

       [[-16, -15, -14, -13],
        [-12, -11, -10,  -9],
        [ -8,  -7,  -6,  -5],
        [ -4,  -3,  -2,  -1]]])

In [77]:
np.stack((b,c),1)

array([[[  0,   1,   2,   3],
        [-16, -15, -14, -13]],

       [[  4,   5,   6,   7],
        [-12, -11, -10,  -9]],

       [[  8,   9,  10,  11],
        [ -8,  -7,  -6,  -5]],

       [[ 12,  13,  14,  15],
        [ -4,  -3,  -2,  -1]]])

In [80]:
# Dividiendo arreglos
np.split(b,4)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [81]:
np.hsplit(b,4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]), array([[ 1],
        [ 5],
        [ 9],
        [13]]), array([[ 2],
        [ 6],
        [10],
        [14]]), array([[ 3],
        [ 7],
        [11],
        [15]])]

In [82]:
np.vsplit(b,4)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [85]:
# Agregar elementos al arreglo
np.append(a,[11,12,13,14])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8, 11, 12, 13, 14])

In [86]:
# Insertar al arreglo en posiciones definidas
np.insert(a, 3, [11,12,13,14])

array([ 0,  1,  2, 11, 12, 13, 14,  3,  4,  5,  6,  7,  8])

In [87]:
# Operaciones elemento a elemento
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [90]:
c

array([[-16, -15, -14, -13],
       [-12, -11, -10,  -9],
       [ -8,  -7,  -6,  -5],
       [ -4,  -3,  -2,  -1]])

In [92]:
b + c 

array([[-16, -14, -12, -10],
       [ -8,  -6,  -4,  -2],
       [  0,   2,   4,   6],
       [  8,  10,  12,  14]])

In [94]:
np.add(b,c)

array([[-16, -14, -12, -10],
       [ -8,  -6,  -4,  -2],
       [  0,   2,   4,   6],
       [  8,  10,  12,  14]])

In [95]:
b - c

array([[16, 16, 16, 16],
       [16, 16, 16, 16],
       [16, 16, 16, 16],
       [16, 16, 16, 16]])

In [97]:
np.subtract(b,c)

array([[16, 16, 16, 16],
       [16, 16, 16, 16],
       [16, 16, 16, 16],
       [16, 16, 16, 16]])

In [98]:
b * c

array([[  0, -15, -28, -39],
       [-48, -55, -60, -63],
       [-64, -63, -60, -55],
       [-48, -39, -28, -15]])

In [99]:
np.multiply(b,c)

array([[  0, -15, -28, -39],
       [-48, -55, -60, -63],
       [-64, -63, -60, -55],
       [-48, -39, -28, -15]])

In [100]:
b/c

array([[ -0.        ,  -0.06666667,  -0.14285714,  -0.23076923],
       [ -0.33333333,  -0.45454545,  -0.6       ,  -0.77777778],
       [ -1.        ,  -1.28571429,  -1.66666667,  -2.2       ],
       [ -3.        ,  -4.33333333,  -7.        , -15.        ]])

In [101]:
np.sqrt(b)

array([[0.        , 1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974, 2.64575131],
       [2.82842712, 3.        , 3.16227766, 3.31662479],
       [3.46410162, 3.60555128, 3.74165739, 3.87298335]])

In [102]:
np.log(b)

/Users/ma0/miniconda3/envs/curso_rapido_python/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([[      -inf, 0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947, 1.94591015],
       [2.07944154, 2.19722458, 2.30258509, 2.39789527],
       [2.48490665, 2.56494936, 2.63905733, 2.7080502 ]])

In [104]:
# Operaciones de agregación
a.sum()

36

In [106]:
b.sum()

120

In [107]:
b.sum(axis=0)

array([24, 28, 32, 36])

In [108]:
b.sum(axis=1)

array([ 6, 22, 38, 54])

In [109]:
b.min()

0

In [110]:
b.max()

15

In [111]:
b.cumsum()

array([  0,   1,   3,   6,  10,  15,  21,  28,  36,  45,  55,  66,  78,
        91, 105, 120])

In [112]:
b.mean()

7.5

In [113]:
b.mean(axis=0)

array([6., 7., 8., 9.])

In [114]:
np.median(b)

7.5

In [116]:
np.median(b, axis=0)

array([6., 7., 8., 9.])

In [117]:
np.std(b)

4.6097722286464435

In [119]:
np.unique(b)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [120]:
# Operaciones entre matrices
b.dot(c)

array([[ -40,  -34,  -28,  -22],
       [-200, -178, -156, -134],
       [-360, -322, -284, -246],
       [-520, -466, -412, -358]])

In [121]:
np.dot(b.T, b)

array([[224, 248, 272, 296],
       [248, 276, 304, 332],
       [272, 304, 336, 368],
       [296, 332, 368, 404]])

In [127]:
# Guardar arreglos
with open("b.numpy", "wb+") as f:
    np.save(f,b)

In [130]:
np.load("b.numpy")

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [131]:
with open("b.txt", "wb+") as f:
    np.savetxt(f,b)

In [132]:
np.loadtxt("b.txt")

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])